### ISSUE TITLE
Snapshot Download Script (https://github.com/fastnear/static/blob/main/down.sh)

### ISSUE THREAD

**Issue by gaia** [fastnear/static#1]
Works well, thanks, Fastnear team!

One suggestion: use aria instead of wget. Even if you use aria do DL one file at a time with one connection (drop in replacing wget), with aria one can set the max bandwidth to be used for the DL.

reworking it to use aria with 20 downloads and one connection is another option, as opposed to manually creating additional threads.

also keep in mind aria's retrying capability, and resuming partial downloads or entire batches.

**Comment by gaia** [comment]
scenarios in which bwidth limits are useful

A) machine downloading shares bandwidth with other machines in the local network (virtualized or not, there are other VMs using the bwidth)

B) machine downloading doesn't share bandwidth with other machines in the local network but it does share a disk which results in increased IOwait.

C) bwidth is only paid past a certain speed, it's unmetered below a certain speed.

or any combination of the above reasons.

**Comment by evgenykuzyakov** [comment]
Updated to use `rclone`
